unit uBuiltins;

interface

uses
  System.SysUtils, System.Generics.Collections;

type
  TOpcodeBase = Word;

const
  O_OPERATOR    = $8000;
  O_INT         = $4000;
  O_FLOAT       = $2000;
  O_STRING      = $1000;
  O_INTOP       = O_OPERATOR or O_INT;
  O_STRINGOP    = O_OPERATOR or O_STRING;
  O_FLOATOP     = O_OPERATOR or O_FLOAT;
  O_NAMEREF     = O_STRINGOP or 1;  // procedure/name table reference (written as offset in INT)

type
  TOpcode = Word;

const
  O_NOOP              = O_OPERATOR + 0;
  O_CONST              = O_OPERATOR + 1;
  O_CRITICAL_START    = O_OPERATOR + 2;
  O_CRITICAL_DONE     = O_OPERATOR + 3;
  O_JMP               = O_OPERATOR + 4;
  O_CALL              = O_OPERATOR + 5;
  O_CALL_AT           = O_OPERATOR + 6;
  O_CALL_CONDITION    = O_OPERATOR + 7;
  O_CALLSTART         = O_OPERATOR + 8;
  O_EXEC              = O_OPERATOR + 9;
  O_SPAWN             = O_OPERATOR + 10;
  O_FORK              = O_OPERATOR + 11;
  O_A_TO_D            = O_OPERATOR + 12;
  O_D_TO_A            = O_OPERATOR + 13;
  O_EXIT              = O_OPERATOR + 14;
  O_DETACH            = O_OPERATOR + 15;
  O_EXIT_PROG         = O_OPERATOR + 16;
  O_STOP_PROG         = O_OPERATOR + 17;
  O_FETCH_GLOBAL     = O_OPERATOR + 18;
  O_STORE_GLOBAL     = O_OPERATOR + 19;
  O_FETCH_EXTERNAL   = O_OPERATOR + 20;
  O_STORE_EXTERNAL   = O_OPERATOR + 21;
  O_EXPORT_VAR       = O_OPERATOR + 22;
  O_EXPORT_PROC      = O_OPERATOR + 23;
  O_SWAP              = O_OPERATOR + 24;
  O_SWAPA             = O_OPERATOR + 25;
  O_POP               = O_OPERATOR + 26;
  O_DUP               = O_OPERATOR + 27;
  O_POP_RETURN       = O_OPERATOR + 28;
  O_POP_EXIT         = O_OPERATOR + 29;
  O_POP_ADDRESS      = O_OPERATOR + 30;
  O_POP_FLAGS        = O_OPERATOR + 31;
  O_POP_FLAGS_RETURN = O_OPERATOR + 32;
  O_POP_FLAGS_EXIT   = O_OPERATOR + 33;
  O_CHECK_ARG_COUNT  = O_OPERATOR + 39;
  O_LOOKUP_STRING_PROC = O_OPERATOR + 40;
  O_POP_BASE         = O_OPERATOR + 41;
  O_POP_TO_BASE     = O_OPERATOR + 42;
  O_PUSH_BASE       = O_OPERATOR + 43;
  O_SET_GLOBAL      = O_OPERATOR + 44;
  O_FETCH_PROC_ADDRESS = O_OPERATOR + 45;
  O_DUMP             = O_OPERATOR + 46;
  O_IF               = O_OPERATOR + 47;
  O_WHILE            = O_OPERATOR + 48;
  O_STORE            = O_OPERATOR + 49;
  O_FETCH            = O_OPERATOR + 50;
  O_EQUAL            = O_OPERATOR + 51;
  O_NOT_EQUAL        = O_OPERATOR + 52;
  O_LESS_EQUAL      = O_OPERATOR + 53;
  O_GREATER_EQUAL   = O_OPERATOR + 54;
  O_LESS            = O_OPERATOR + 55;
  O_GREATER         = O_OPERATOR + 56;
  O_ADD             = O_OPERATOR + 57;
  O_SUB             = O_OPERATOR + 58;
  O_MUL             = O_OPERATOR + 59;
  O_DIV             = O_OPERATOR + 60;
  O_MOD             = O_OPERATOR + 61;
  O_AND             = O_OPERATOR + 62;
  O_OR              = O_OPERATOR + 63;
  O_BWAND           = O_OPERATOR + 64;
  O_BWOR            = O_OPERATOR + 65;
  O_BWXOR           = O_OPERATOR + 66;
  O_BWNOT           = O_OPERATOR + 67;
  O_FLOOR           = O_OPERATOR + 68;
  O_NOT             = O_OPERATOR + 69;
  O_NEGATE          = O_OPERATOR + 70;
  O_WAIT             = O_OPERATOR + 71;
  O_CANCEL          = O_OPERATOR + 72;
  O_CANCELALL       = O_OPERATOR + 73;
  O_STARTCRITICAL   = O_OPERATOR + 74;
  O_ENDCRITICAL     = O_OPERATOR + 75;
  O_END_CORE       = O_OPERATOR + 76;
  O_RET            = O_OPERATOR + 77;

  // ========================================================================
  // Fallout 2 engine opcodes (opextra.h — matching sfall edition)
  // These are the direct opcodes emitted for builtin function calls.
  // ========================================================================

  // Library opcodes (oplib.h) — dialogue, window, display, sound, etc.
  O_SAYQUIT           = O_END_CORE + 1;
  O_SAYEND            = O_END_CORE + 2;
  O_SAYSTART          = O_END_CORE + 3;
  O_SAYSTARTPOS       = O_END_CORE + 4;
  O_SAYREPLYTITLE     = O_END_CORE + 5;
  O_SAYGOTOREPLY      = O_END_CORE + 6;
  O_SAYREPLY          = O_END_CORE + 7;
  O_SAYOPTION         = O_END_CORE + 8;
  O_SAYMESSAGE        = O_END_CORE + 9;
  O_SAYREPLYWINDOW    = O_END_CORE + 10;
  O_SAYOPTIONWINDOW   = O_END_CORE + 11;
  O_SAYBORDER         = O_END_CORE + 12;
  O_SAYSCROLLUP       = O_END_CORE + 13;
  O_SAYSCROLLDOWN     = O_END_CORE + 14;
  O_SAYSETSPACING     = O_END_CORE + 15;
  O_SAYOPTIONCOLOR    = O_END_CORE + 16;
  O_SAYREPLYCOLOR     = O_END_CORE + 17;
  O_SAYRESTART        = O_END_CORE + 18;
  O_SAYGETLASTPOS     = O_END_CORE + 19;
  O_SAYREPLYFLAGS     = O_END_CORE + 20;
  O_SAYOPTIONFLAGS    = O_END_CORE + 21;
  O_SAYMESSAGETIMEOUT = O_END_CORE + 22;
  O_CREATEWIN         = O_END_CORE + 23;
  O_DELETEWIN         = O_END_CORE + 24;
  O_SELECTWIN         = O_END_CORE + 25;
  O_RESIZEWIN         = O_END_CORE + 26;
  O_SCALEWIN          = O_END_CORE + 27;
  O_SHOWWIN           = O_END_CORE + 28;
  O_FILLWIN           = O_END_CORE + 29;
  O_FILLRECT          = O_END_CORE + 30;
  O_FILLWIN3X3        = O_END_CORE + 31;
  O_DISPLAY           = O_END_CORE + 32;
  O_DISPLAYGFX        = O_END_CORE + 33;
  O_DISPLAYRAW        = O_END_CORE + 34;
  O_LOADPALETTETABLE  = O_END_CORE + 35;
  O_FADEIN            = O_END_CORE + 36;
  O_FADEOUT           = O_END_CORE + 37;
  O_GOTOXY            = O_END_CORE + 38;
  O_PRINT             = O_END_CORE + 39;
  O_FORMAT            = O_END_CORE + 40;
  O_PRINTRECT         = O_END_CORE + 41;
  O_SETFONT           = O_END_CORE + 42;
  O_SETTEXTFLAGS      = O_END_CORE + 43;
  O_SETTEXTCOLOR      = O_END_CORE + 44;
  O_SETHIGHLIGHTCOLOR = O_END_CORE + 45;
  O_STOPMOVIE         = O_END_CORE + 46;
  O_PLAYMOVIE         = O_END_CORE + 47;
  O_MOVIEFLAGS        = O_END_CORE + 48;
  O_PLAYMOVIERECT     = O_END_CORE + 49;
  O_PLAYMOVIEALPHA    = O_END_CORE + 50;
  O_PLAYMOVIEALPHARECT= O_END_CORE + 51;
  O_ADDREGION         = O_END_CORE + 52;
  O_ADDREGIONFLAG     = O_END_CORE + 53;
  O_ADDREGIONPROC     = O_END_CORE + 54;
  O_ADDREGIONRIGHTPROC= O_END_CORE + 55;
  O_DELETEREGION      = O_END_CORE + 56;
  O_ACTIVATEREGION    = O_END_CORE + 57;
  O_CHECKREGION       = O_END_CORE + 58;
  O_ADDBUTTON         = O_END_CORE + 59;
  O_ADDBUTTONTEXT     = O_END_CORE + 60;
  O_ADDBUTTONFLAG     = O_END_CORE + 61;
  O_ADDBUTTONGFX      = O_END_CORE + 62;
  O_ADDBUTTONPROC     = O_END_CORE + 63;
  O_ADDBUTTONRIGHTPROC= O_END_CORE + 64;
  O_DELETEBUTTON      = O_END_CORE + 65;
  O_HIDEMOUSE         = O_END_CORE + 66;
  O_SHOWMOUSE         = O_END_CORE + 67;
  O_MOUSESHAPE        = O_END_CORE + 68;
  O_REFRESHMOUSE      = O_END_CORE + 69;
  O_SETGLOBALMOUSEFUNC= O_END_CORE + 70;
  O_ADDNAMEDEVENT     = O_END_CORE + 71;
  O_ADDNAMEDHANDLER   = O_END_CORE + 72;
  O_CLEARNAMED        = O_END_CORE + 73;
  O_SIGNALNAMED       = O_END_CORE + 74;
  O_ADDKEY            = O_END_CORE + 75;
  O_DELETEKEY         = O_END_CORE + 76;
  O_SOUNDPLAY          = O_END_CORE + 77;
  O_SOUNDPAUSE        = O_END_CORE + 78;
  O_SOUNDRESUME       = O_END_CORE + 79;
  O_SOUNDSTOP         = O_END_CORE + 80;
  O_SOUNDREWIND       = O_END_CORE + 81;
  O_SOUNDDELETE       = O_END_CORE + 82;
  O_SETONEOPTPAUSE    = O_END_CORE + 83;
  O_SELECTFILELIST    = O_END_CORE + 84;
  O_TOKENIZE          = O_END_CORE + 85;
  O_END_LIB           = O_END_CORE + 86;

  // Fallout 2 engine opcodes (opextra.h)
  O_GIVE_EXP_POINTS     = O_END_LIB + 1;
  O_SCR_RETURN          = O_END_LIB + 2;
  O_PLAY_SFX            = O_END_LIB + 3;
  O_OBJ_NAME            = O_END_LIB + 4;
  O_SFX_BUILD_OPEN_NAME = O_END_LIB + 5;
  O_GET_PC_STAT         = O_END_LIB + 6;
  O_TILE_CONTAINS_PID   = O_END_LIB + 7;
  O_SET_MAP_START       = O_END_LIB + 8;
  O_OVERRIDE_MAP_START  = O_END_LIB + 9;
  O_HAS_SKILL           = O_END_LIB + 10;
  O_USING_SKILL         = O_END_LIB + 11;
  O_ROLL_VS_SKILL       = O_END_LIB + 12;
  O_SKILL_CONTEST       = O_END_LIB + 13;
  O_DO_CHECK            = O_END_LIB + 14;
  O_IS_SUCCESS          = O_END_LIB + 15;
  O_IS_CRITICAL         = O_END_LIB + 16;
  O_HOW_MUCH            = O_END_LIB + 17;
  O_MARK_AREA_KNOWN     = O_END_LIB + 18;
  O_REACTION_INFLUENCE  = O_END_LIB + 19;
  O_RANDOM              = O_END_LIB + 20;
  O_ROLL_DICE           = O_END_LIB + 21;
  O_MOVE_TO             = O_END_LIB + 22;
  O_CREATE_OBJECT_SID   = O_END_LIB + 23;
  O_DISPLAY_MSG         = O_END_LIB + 24;
  O_SCRIPT_OVERRIDES    = O_END_LIB + 25;
  O_OBJ_IS_CARRYING_PID = O_END_LIB + 26;
  O_TILE_CONTAINS_PID_OBJ= O_END_LIB + 27;
  O_SELF_OBJ            = O_END_LIB + 28;
  O_SOURCE_OBJ          = O_END_LIB + 29;
  O_TARGET_OBJ          = O_END_LIB + 30;
  O_DUDE_OBJ            = O_END_LIB + 31;
  O_OBJ_BEING_USED_WITH = O_END_LIB + 32;
  O_LOCAL_VAR           = O_END_LIB + 33;
  O_SET_LOCAL_VAR       = O_END_LIB + 34;
  O_MAP_VAR             = O_END_LIB + 35;
  O_SET_MAP_VAR         = O_END_LIB + 36;
  O_GLOBAL_VAR          = O_END_LIB + 37;
  O_SET_GLOBAL_VAR      = O_END_LIB + 38;
  O_SCRIPT_ACTION       = O_END_LIB + 39;
  O_OBJ_TYPE            = O_END_LIB + 40;
  O_OBJ_ITEM_SUBTYPE    = O_END_LIB + 41;
  O_GET_CRITTER_STAT    = O_END_LIB + 42;
  O_SET_CRITTER_STAT    = O_END_LIB + 43;
  O_ANIMATE_STAND_OBJ   = O_END_LIB + 44;
  O_ANIMATE_STAND_REV   = O_END_LIB + 45;
  O_ANIMATE_MOVE_TO_TILE= O_END_LIB + 46;
  O_TILE_IN_TILE_RECT   = O_END_LIB + 47;
  O_ATTACK_COMPLEX      = O_END_LIB + 48;
  O_MAKE_DAYTIME        = O_END_LIB + 49;
  O_TILE_DISTANCE       = O_END_LIB + 50;
  O_TILE_DISTANCE_OBJS  = O_END_LIB + 51;
  O_TILE_NUM            = O_END_LIB + 52;
  O_TILE_NUM_IN_DIR     = O_END_LIB + 53;
  O_PICKUP_OBJ          = O_END_LIB + 54;
  O_DROP_OBJ            = O_END_LIB + 55;
  O_ADD_OBJ_TO_INVEN    = O_END_LIB + 56;
  O_RM_OBJ_FROM_INVEN   = O_END_LIB + 57;
  O_WIELD_OBJ_CRITTER   = O_END_LIB + 58;
  O_USE_OBJ             = O_END_LIB + 59;
  O_OBJ_CAN_SEE_OBJ     = O_END_LIB + 60;
  O_ATTACK              = O_END_LIB + 61;
  O_START_GDIALOG       = O_END_LIB + 62;
  O_END_DIALOGUE        = O_END_LIB + 63;
  O_DIALOGUE_REACTION   = O_END_LIB + 64;
  O_METARULE3           = O_END_LIB + 65;
  O_SET_MAP_MUSIC       = O_END_LIB + 66;
  O_SET_OBJ_VISIBILITY  = O_END_LIB + 67;
  O_LOAD_MAP            = O_END_LIB + 68;
  O_SET_EXIT_GRIDS      = O_END_LIB + 69;
  O_ANIM_BUSY           = O_END_LIB + 70;
  O_CRITTER_HEAL        = O_END_LIB + 71;
  O_SET_LIGHT_LEVEL     = O_END_LIB + 72;
  O_GAME_TIME           = O_END_LIB + 73;
  O_GAME_TIME_SECONDS   = O_END_LIB + 74;
  O_ELEVATION           = O_END_LIB + 75;
  O_KILL_CRITTER        = O_END_LIB + 76;
  O_KILL_CRITTER_TYPE   = O_END_LIB + 77;
  O_CRITTER_DMG         = O_END_LIB + 78;
  O_ADD_TIMER_EVENT     = O_END_LIB + 79;
  O_RM_TIMER_EVENT      = O_END_LIB + 80;
  O_GAME_TICKS          = O_END_LIB + 81;
  O_HAS_TRAIT           = O_END_LIB + 82;
  O_DESTROY_OBJECT      = O_END_LIB + 83;
  O_OBJ_CAN_HEAR_OBJ   = O_END_LIB + 84;
  O_GAME_TIME_HOUR      = O_END_LIB + 85;
  O_FIXED_PARAM         = O_END_LIB + 86;
  O_TILE_IS_VISIBLE     = O_END_LIB + 87;
  O_DIALOGUE_SYS_ENTER  = O_END_LIB + 88;
  O_ACTION_BEING_USED   = O_END_LIB + 89;
  O_CRITTER_STATE       = O_END_LIB + 90;
  O_GAME_TIME_ADVANCE   = O_END_LIB + 91;
  O_RADIATION_INC       = O_END_LIB + 92;
  O_RADIATION_DEC       = O_END_LIB + 93;
  O_CRITTER_ATTEMPT_PLAC= O_END_LIB + 94;
  O_OBJ_PID             = O_END_LIB + 95;
  O_CUR_MAP_INDEX       = O_END_LIB + 96;
  O_CRITTER_ADD_TRAIT   = O_END_LIB + 97;
  O_CRITTER_RM_TRAIT    = O_END_LIB + 98;
  O_PROTO_DATA          = O_END_LIB + 99;
  O_MESSAGE_STR         = O_END_LIB + 100;
  O_CRITTER_INVEN_OBJ   = O_END_LIB + 101;
  O_OBJ_SET_LIGHT_LEVEL = O_END_LIB + 102;
  O_WORLD_MAP           = O_END_LIB + 103;
  O_FLOAT_MSG           = O_END_LIB + 105;
  O_METARULE            = O_END_LIB + 106;
  O_ANIM                = O_END_LIB + 107;
  O_OBJ_CARRYING_PID    = O_END_LIB + 108;
  O_REG_ANIM_FUNC       = O_END_LIB + 109;
  O_REG_ANIM_ANIMATE    = O_END_LIB + 110;
  O_REG_ANIM_ANIMATE_REV= O_END_LIB + 111;
  O_REG_ANIM_MOVE_TO_OBJ= O_END_LIB + 112;
  O_REG_ANIM_RUN_TO_OBJ = O_END_LIB + 113;
  O_REG_ANIM_MOVE_TO_TILE= O_END_LIB + 114;
  O_REG_ANIM_RUN_TO_TILE= O_END_LIB + 115;
  O_PLAY_GMOVIE         = O_END_LIB + 116;
  O_ADD_MULT_OBJS       = O_END_LIB + 117;
  O_RM_MULT_OBJS        = O_END_LIB + 118;
  O_GET_MONTH           = O_END_LIB + 119;
  O_GET_DAY             = O_END_LIB + 120;
  O_EXPLOSION           = O_END_LIB + 121;
  O_DAYS_SINCE_VISITED  = O_END_LIB + 122;
  O_GSAY_START          = O_END_LIB + 123;
  O_GSAY_END            = O_END_LIB + 124;
  O_GSAY_REPLY          = O_END_LIB + 125;
  O_GSAY_OPTION         = O_END_LIB + 126;
  O_GSAY_MESSAGE        = O_END_LIB + 127;
  O_GIQ_OPTION          = O_END_LIB + 128;
  O_POISON              = O_END_LIB + 129;
  O_GET_POISON          = O_END_LIB + 130;
  O_PARTY_ADD           = O_END_LIB + 131;
  O_PARTY_REMOVE        = O_END_LIB + 132;
  O_REG_ANIM_FOREVER    = O_END_LIB + 133;
  O_CRITTER_INJURE      = O_END_LIB + 134;
  O_COMBAT_IS_INIT      = O_END_LIB + 135;
  O_GDIALOG_BARTER_MOD  = O_END_LIB + 136;
  O_DIFFICULTY_LEVEL    = O_END_LIB + 137;
  O_RUNNING_BURNING_GUY = O_END_LIB + 138;
  O_INVEN_UNWIELD       = O_END_LIB + 139;
  O_OBJ_IS_LOCKED       = O_END_LIB + 140;
  O_OBJ_LOCK            = O_END_LIB + 141;
  O_OBJ_UNLOCK          = O_END_LIB + 142;
  O_OBJ_IS_OPEN         = O_END_LIB + 143;
  O_OBJ_OPEN             = O_END_LIB + 144;
  O_OBJ_CLOSE            = O_END_LIB + 145;
  O_GAME_UI_DISABLE     = O_END_LIB + 146;
  O_GAME_UI_ENABLE      = O_END_LIB + 147;
  O_GAME_UI_IS_DISABLED = O_END_LIB + 148;
  O_GFADE_OUT           = O_END_LIB + 149;
  O_GFADE_IN            = O_END_LIB + 150;
  O_ITEM_CAPS_TOTAL     = O_END_LIB + 151;
  O_ITEM_CAPS_ADJUST    = O_END_LIB + 152;
  O_ANIM_ACTION_FRAME   = O_END_LIB + 153;
  O_REG_ANIM_PLAY_SFX   = O_END_LIB + 154;
  O_CRITTER_MOD_SKILL   = O_END_LIB + 155;
  O_SFX_BUILD_CHAR_NAME = O_END_LIB + 156;
  O_SFX_BUILD_AMBIENT   = O_END_LIB + 157;
  O_SFX_BUILD_INTERFACE = O_END_LIB + 158;
  O_SFX_BUILD_ITEM_NAME = O_END_LIB + 159;
  O_SFX_BUILD_WEAPON    = O_END_LIB + 160;
  O_SFX_BUILD_SCENERY   = O_END_LIB + 161;
  O_ATTACK_SETUP        = O_END_LIB + 162;
  O_DESTROY_MULT_OBJS   = O_END_LIB + 163;
  O_USE_OBJ_ON_OBJ      = O_END_LIB + 164;
  O_ENDGAME_SLIDESHOW   = O_END_LIB + 165;
  O_MOVE_OBJ_INVEN      = O_END_LIB + 166;
  O_ENDGAME_MOVIE       = O_END_LIB + 167;
  O_OBJ_ART_FID         = O_END_LIB + 168;
  O_ART_ANIM            = O_END_LIB + 169;
  O_PARTY_MEMBER_OBJ    = O_END_LIB + 170;
  O_ROTATION_TO_TILE    = O_END_LIB + 171;
  O_JAM_LOCK            = O_END_LIB + 172;
  O_SET_BARTER_MOD      = O_END_LIB + 173;
  O_COMBAT_DIFFICULTY   = O_END_LIB + 174;
  O_OBJ_ON_SCREEN       = O_END_LIB + 175;
  O_CRITTER_IS_FLEEING  = O_END_LIB + 176;
  O_CRITTER_SET_FLEE    = O_END_LIB + 177;
  O_TERMINATE_COMBAT    = O_END_LIB + 178;
  O_DEBUG_MSG           = O_END_LIB + 179;
  O_CRITTER_STOP_ATTACK = O_END_LIB + 180;

  OP_PUSH_NUMBER    = $01;
  OP_PUSH_STRING    = $02;
  OP_PUSH_VARIABLE  = $03;
  OP_POP            = $04;
  OP_DUP            = $05;
  OP_SWAP            = $06;
  OP_ADD            = $10;
  OP_SUB            = $11;
  OP_MUL            = $12;
  OP_DIV            = $13;
  OP_MOD            = $14;
  OP_NEG            = $15;
  OP_EQ             = $20;
  OP_NE             = $21;
  OP_LT             = $22;
  OP_GT             = $23;
  OP_LE             = $24;
  OP_GE             = $25;
  OP_AND            = $30;
  OP_OR             = $31;
  OP_NOT            = $32;
  OP_JMP            = $40;
  OP_JZ             = $41;
  OP_JNZ            = $42;
  OP_CALL_PROC      = $50;
  OP_CALL_BUILTIN   = $51;
  OP_RET            = $52;
  OP_PUSH_LOCAL    = $60;
  OP_POP_LOCAL     = $61;
  OP_PUSH_GLOBAL   = $62;
  OP_POP_GLOBAL    = $63;
  OP_PUSH_MAPVAR   = $64;
  OP_POP_MAPVAR    = $65;
  OP_PUSH_TEMP     = $66;
  OP_POP_TEMP      = $67;
  OP_NOP            = $FF;

type
  TBuiltinFunction = record
    Name: string;
    OpcodeID: Word;       // builtin ID for LOOKUP_STRING_PROC approach
    SfallOpcode: Word;    // direct sfall opcode (0 = unknown, use LOOKUP_STRING_PROC)
    ParamCount: Integer;
    ReturnType: Integer;
  end;

  TBuiltinDatabase = class
  private
    FFunctions: TDictionary<string, TBuiltinFunction>;
    FIDMap: TDictionary<Word, TBuiltinFunction>;
  public
    constructor Create;
    destructor Destroy; override;
    procedure RegisterFunction(const AName: string; AID: Word; AParams: Integer; ARetType: Integer; ASfallOpcode: Word = 0);
    function FindByName(const AName: string): TBuiltinFunction;
    function FindByID(AID: Word): TBuiltinFunction;
    function FindSfallOpcode(const AName: string): Word;
    procedure InitializeFallout2Builtins;
  end;

implementation

constructor TBuiltinDatabase.Create;
begin
  inherited;
  FFunctions := TDictionary<string, TBuiltinFunction>.Create;
  FIDMap := TDictionary<Word, TBuiltinFunction>.Create;
end;

destructor TBuiltinDatabase.Destroy;
begin
  FFunctions.Free;
  FIDMap.Free;
  inherited;
end;

procedure TBuiltinDatabase.RegisterFunction(const AName: string; AID: Word;
  AParams: Integer; ARetType: Integer; ASfallOpcode: Word = 0);
var
  Func: TBuiltinFunction;
begin
  Func.Name := AName;
  Func.OpcodeID := AID;
  Func.SfallOpcode := ASfallOpcode;
  Func.ParamCount := AParams;
  Func.ReturnType := ARetType;
  FFunctions.AddOrSetValue(LowerCase(AName), Func);
  FIDMap.AddOrSetValue(AID, Func);
end;

function TBuiltinDatabase.FindByName(const AName: string): TBuiltinFunction;
begin
  if not FFunctions.TryGetValue(LowerCase(AName), Result) then
    raise Exception.CreateFmt('Unknown builtin function: %s', [AName]);
end;

function TBuiltinDatabase.FindByID(AID: Word): TBuiltinFunction;
begin
  if not FIDMap.TryGetValue(AID, Result) then
    raise Exception.CreateFmt('Unknown builtin ID: %d', [AID]);
end;

function TBuiltinDatabase.FindSfallOpcode(const AName: string): Word;
var
  Func: TBuiltinFunction;
begin
  if FFunctions.TryGetValue(LowerCase(AName), Func) then
    Result := Func.SfallOpcode
  else
    Result := 0;
end;

procedure TBuiltinDatabase.InitializeFallout2Builtins;
begin
  // Builtins with sfall opcodes use the direct opcode approach.
  // Builtins with 0 sfall opcode fall back to LOOKUP_STRING_PROC + CALL.
  RegisterFunction('display_msg', $0001, 1, 0, O_DISPLAY_MSG);
  RegisterFunction('debug_msg', $0002, 1, 0, O_DEBUG_MSG);
  RegisterFunction('float_msg', $0003, 3, 0, O_FLOAT_MSG);
  RegisterFunction('message_str', $0004, 2, 2, O_MESSAGE_STR);
  RegisterFunction('message_str_game', $0005, 2, 2);
  RegisterFunction('create_object', $0100, 3, 3);
  RegisterFunction('create_object_sid', $0101, 4, 3, O_CREATE_OBJECT_SID);
  RegisterFunction('obj_name', $0102, 1, 2, O_OBJ_NAME);
  RegisterFunction('obj_art_fid', $0103, 1, 1, O_OBJ_ART_FID);
  RegisterFunction('obj_pid', $0104, 1, 1, O_OBJ_PID);
  RegisterFunction('obj_is_carrying_obj_pid', $0105, 2, 1, O_OBJ_IS_CARRYING_PID);
  RegisterFunction('obj_carrying_pid_obj', $0106, 2, 3, O_OBJ_CARRYING_PID);
  RegisterFunction('obj_can_see_obj', $0107, 2, 1, O_OBJ_CAN_SEE_OBJ);
  RegisterFunction('obj_can_hear_obj', $0108, 2, 1, O_OBJ_CAN_HEAR_OBJ);
  RegisterFunction('attack', $0200, 1, 0, O_ATTACK);
  RegisterFunction('attack_complex', $0201, 5, 0, O_ATTACK_COMPLEX);
  RegisterFunction('evaluate_attack', $0202, 1, 1);
  RegisterFunction('aim_skill', $0203, 2, 1);
  RegisterFunction('party_add', $0300, 1, 0, O_PARTY_ADD);
  RegisterFunction('party_remove', $0301, 1, 0, O_PARTY_REMOVE);
  RegisterFunction('party_member_obj', $0302, 1, 3, O_PARTY_MEMBER_OBJ);
  RegisterFunction('is_party_member', $0303, 1, 1);
  RegisterFunction('add_obj_to_inven', $0400, 2, 0, O_ADD_OBJ_TO_INVEN);
  RegisterFunction('rm_obj_from_inven', $0401, 2, 0, O_RM_OBJ_FROM_INVEN);
  RegisterFunction('add_mult_objs_to_inven', $0402, 3, 0, O_ADD_MULT_OBJS);
  RegisterFunction('move_obj_inven_to_obj', $0403, 2, 0, O_MOVE_OBJ_INVEN);
  RegisterFunction('obj_unequip', $0404, 1, 0, O_INVEN_UNWIELD);
  RegisterFunction('obj_inven_obj', $0405, 2, 3, O_CRITTER_INVEN_OBJ);
  RegisterFunction('critter_heal', $0500, 2, 0, O_CRITTER_HEAL);
  RegisterFunction('critter_dmg', $0501, 3, 0, O_CRITTER_DMG);
  RegisterFunction('critter_set_floating', $0502, 2, 0);
  RegisterFunction('critter_attempt_placement', $0503, 3, 1, O_CRITTER_ATTEMPT_PLAC);
  RegisterFunction('skill_check', $0600, 3, 1);
  RegisterFunction('do_check', $0601, 3, 1, O_DO_CHECK);
  RegisterFunction('roll_vs_skill', $0602, 3, 1, O_ROLL_VS_SKILL);
  RegisterFunction('has_skill', $0603, 2, 1, O_HAS_SKILL);
  RegisterFunction('pc_skill_level', $0604, 2, 1);
  RegisterFunction('local_var', $0700, 1, 1, O_LOCAL_VAR);
  RegisterFunction('set_local_var', $0701, 2, 0, O_SET_LOCAL_VAR);
  RegisterFunction('global_var', $0702, 1, 1, O_GLOBAL_VAR);
  RegisterFunction('set_global_var', $0703, 2, 0, O_SET_GLOBAL_VAR);
  RegisterFunction('map_var', $0704, 1, 1, O_MAP_VAR);
  RegisterFunction('set_map_var', $0705, 2, 0, O_SET_MAP_VAR);
  RegisterFunction('game_ticks', $0800, 0, 1, O_GAME_TICKS);
  RegisterFunction('game_time', $0801, 0, 1, O_GAME_TIME);
  RegisterFunction('elevation', $0802, 1, 1, O_ELEVATION);
  RegisterFunction('tile_distance', $0803, 2, 1, O_TILE_DISTANCE);
  RegisterFunction('tile_distance_objs', $0804, 2, 1, O_TILE_DISTANCE_OBJS);
  RegisterFunction('dude_obj', $0900, 0, 3, O_DUDE_OBJ);
  RegisterFunction('dude_is_male', $0901, 0, 1);
  RegisterFunction('give_exp_points', $0902, 1, 0, O_GIVE_EXP_POINTS);
  RegisterFunction('get_pc_stat', $0903, 1, 1, O_GET_PC_STAT);
  RegisterFunction('has_quest', $0A00, 1, 1);
  RegisterFunction('set_quest', $0A01, 1, 0);
  RegisterFunction('rep_good', $0A02, 0, 1);
  RegisterFunction('rep_bad', $0A03, 0, 1);
  RegisterFunction('rep_good_vault', $0A04, 0, 1);
  RegisterFunction('add_timer_event', $0B00, 3, 0, O_ADD_TIMER_EVENT);
  RegisterFunction('rm_timer_event', $0B01, 1, 0, O_RM_TIMER_EVENT);
  RegisterFunction('fix_timer_event', $0B02, 4, 0);
  RegisterFunction('random', $0C00, 2, 1, O_RANDOM);
  RegisterFunction('metarule', $0C01, 2, 1, O_METARULE);
  RegisterFunction('metarule3', $0C02, 4, 1, O_METARULE3);
  RegisterFunction('script_action', $0C03, 0, 1, O_SCRIPT_ACTION);
  RegisterFunction('obj_is_locked', $0C04, 1, 1, O_OBJ_IS_LOCKED);
  RegisterFunction('obj_lock', $0C05, 1, 0, O_OBJ_LOCK);
  RegisterFunction('obj_unlock', $0C06, 1, 0, O_OBJ_UNLOCK);
  // Second set — sfall opcode names
  RegisterFunction('give_exp_points', $1000, 1, 0, O_GIVE_EXP_POINTS);
  RegisterFunction('scr_return', $1001, 0, 0, O_SCR_RETURN);
  RegisterFunction('play_sfx', $1002, 2, 0, O_PLAY_SFX);
  RegisterFunction('obj_name', $1003, 1, 2, O_OBJ_NAME);
  RegisterFunction('sfx_build_open_name', $1004, 1, 2, O_SFX_BUILD_OPEN_NAME);
  RegisterFunction('get_pc_stat', $1005, 1, 1, O_GET_PC_STAT);
  RegisterFunction('tile_contains_pid_obj', $1006, 2, 3, O_TILE_CONTAINS_PID_OBJ);
  RegisterFunction('set_map_start', $1007, 3, 0, O_SET_MAP_START);
  RegisterFunction('override_map_start', $1008, 3, 0, O_OVERRIDE_MAP_START);
  RegisterFunction('has_skill', $1009, 2, 1, O_HAS_SKILL);
  RegisterFunction('using_skill', $100A, 1, 1, O_USING_SKILL);
  RegisterFunction('roll_vs_skill', $100B, 3, 1, O_ROLL_VS_SKILL);
  RegisterFunction('skill_contest', $100C, 3, 1, O_SKILL_CONTEST);
  RegisterFunction('do_check', $100D, 3, 1, O_DO_CHECK);
  RegisterFunction('do_check', $100D, 3, 1);
  RegisterFunction('is_success', $100E, 0, 1, O_IS_SUCCESS);
  RegisterFunction('is_critical', $100F, 0, 1, O_IS_CRITICAL);
  RegisterFunction('how_much', $1010, 0, 1, O_HOW_MUCH);
  RegisterFunction('mark_area_known', $1011, 2, 0, O_MARK_AREA_KNOWN);
  RegisterFunction('reaction', $1012, 0, 1, O_REACTION_INFLUENCE);
  RegisterFunction('random', $1013, 2, 1, O_RANDOM);
  RegisterFunction('roll_dice', $1014, 3, 1, O_ROLL_DICE);
  RegisterFunction('move_to', $1015, 2, 0, O_MOVE_TO);
  RegisterFunction('create_object_sid', $1016, 4, 3, O_CREATE_OBJECT_SID);
  RegisterFunction('display_msg', $1017, 1, 0, O_DISPLAY_MSG);
  RegisterFunction('script_overrides', $1018, 0, 1, O_SCRIPT_OVERRIDES);
  RegisterFunction('obj_is_carying_obj_pid', $1019, 2, 1, O_OBJ_IS_CARRYING_PID);
  RegisterFunction('tile_contains_obj_pid', $101A, 2, 1, O_TILE_CONTAINS_PID_OBJ);
  RegisterFunction('self_obj', $101B, 0, 3, O_SELF_OBJ);
  RegisterFunction('source_obj', $101C, 0, 3, O_SOURCE_OBJ);
  RegisterFunction('target_obj', $101D, 0, 3, O_TARGET_OBJ);
  RegisterFunction('dude_obj', $101E, 0, 3, O_DUDE_OBJ);
  RegisterFunction('obj_being_used_with', $101F, 2, 3, O_OBJ_BEING_USED_WITH);
  RegisterFunction('local_var', $1020, 1, 1, O_LOCAL_VAR);
  RegisterFunction('set_local_var', $1021, 2, 0, O_SET_LOCAL_VAR);
  RegisterFunction('map_var', $1022, 1, 1, O_MAP_VAR);
  RegisterFunction('set_map_var', $1023, 2, 0, O_SET_MAP_VAR);
  RegisterFunction('global_var', $1024, 1, 1, O_GLOBAL_VAR);
  RegisterFunction('set_global_var', $1025, 2, 0, O_SET_GLOBAL_VAR);
  RegisterFunction('script_action', $1026, 0, 1, O_SCRIPT_ACTION);
  RegisterFunction('obj_type', $1027, 1, 1, O_OBJ_TYPE);
  RegisterFunction('obj_item_subtype', $1028, 1, 1, O_OBJ_ITEM_SUBTYPE);
  RegisterFunction('get_critter_stat', $1029, 2, 1, O_GET_CRITTER_STAT);
  RegisterFunction('set_critter_stat', $102A, 3, 0, O_SET_CRITTER_STAT);
  RegisterFunction('animate_stand_obj', $102B, 1, 0, O_ANIMATE_STAND_OBJ);
  RegisterFunction('animate_stand_reverse_obj', $102C, 1, 0, O_ANIMATE_STAND_REV);
  RegisterFunction('animate_move_obj_to_tile', $102D, 3, 0, O_ANIMATE_MOVE_TO_TILE);
  RegisterFunction('tile_in_tile_rect', $102E, 5, 1, O_TILE_IN_TILE_RECT);
  RegisterFunction('metarule3', $102F, 4, 1, O_METARULE3);
  RegisterFunction('set_map_music', $1030, 2, 0, O_SET_MAP_MUSIC);
  RegisterFunction('anim_busy', $1031, 1, 0, O_ANIM_BUSY);
  RegisterFunction('critter_heal', $1032, 2, 0, O_CRITTER_HEAL);
  RegisterFunction('set_light_level', $1033, 1, 0, O_SET_LIGHT_LEVEL);
  RegisterFunction('game_time', $1034, 0, 1, O_GAME_TIME);
  RegisterFunction('game_time_in_seconds', $1035, 0, 1, O_GAME_TIME_SECONDS);
  RegisterFunction('elevation', $1036, 1, 1, O_ELEVATION);
  RegisterFunction('kill_critter', $1037, 1, 0, O_KILL_CRITTER);
  RegisterFunction('kill_critter_type', $1038, 2, 0, O_KILL_CRITTER_TYPE);
  RegisterFunction('critter_dmg', $1039, 3, 0, O_CRITTER_DMG);
  RegisterFunction('add_timer_event', $103A, 3, 0, O_ADD_TIMER_EVENT);
  RegisterFunction('rm_timer_event', $103B, 1, 0, O_RM_TIMER_EVENT);
  RegisterFunction('game_ticks', $103C, 0, 1, O_GAME_TICKS);
  RegisterFunction('has_trait', $103D, 2, 1, O_HAS_TRAIT);
  RegisterFunction('destroy_object', $103E, 1, 0, O_DESTROY_OBJECT);
  RegisterFunction('obj_can_hear_obj', $103F, 2, 1, O_OBJ_CAN_HEAR_OBJ);
  RegisterFunction('game_time_hour', $1040, 0, 1, O_GAME_TIME_HOUR);
  RegisterFunction('fixed_param', $1041, 0, 1, O_FIXED_PARAM);
  RegisterFunction('tile_is_visible', $1042, 2, 1, O_TILE_IS_VISIBLE);
  RegisterFunction('dialogue_system_enter', $1043, 0, 0, O_DIALOGUE_SYS_ENTER);
  RegisterFunction('action_being_used', $1044, 1, 3, O_ACTION_BEING_USED);
  RegisterFunction('critter_state', $1045, 1, 1, O_CRITTER_STATE);
  RegisterFunction('game_time_advance', $1046, 1, 0, O_GAME_TIME_ADVANCE);
  RegisterFunction('radiation_inc', $1047, 2, 0, O_RADIATION_INC);
  RegisterFunction('radiation_dec', $1048, 2, 0, O_RADIATION_DEC);
  RegisterFunction('critter_attempt_placement', $1049, 3, 1, O_CRITTER_ATTEMPT_PLAC);
  RegisterFunction('obj_pid', $104A, 1, 1, O_OBJ_PID);
  RegisterFunction('cur_map_index', $104B, 0, 1, O_CUR_MAP_INDEX);
  RegisterFunction('critter_add_trait', $104C, 3, 0, O_CRITTER_ADD_TRAIT);
  RegisterFunction('critter_rm_trait', $104D, 3, 0, O_CRITTER_RM_TRAIT);
  RegisterFunction('proto_data', $104E, 2, 1, O_PROTO_DATA);
  RegisterFunction('message_str', $104F, 2, 2, O_MESSAGE_STR);
  RegisterFunction('critter_inven_obj', $1050, 2, 3, O_CRITTER_INVEN_OBJ);
  RegisterFunction('obj_set_light_level', $1051, 2, 0, O_OBJ_SET_LIGHT_LEVEL);
  RegisterFunction('world_map', $1052, 0, 0, O_WORLD_MAP);
  RegisterFunction('float_msg', $1053, 3, 0, O_FLOAT_MSG);
  RegisterFunction('metarule', $1054, 2, 1, O_METARULE);
  RegisterFunction('anim', $1055, 2, 0, O_ANIM);
  RegisterFunction('obj_carying_pid_obj', $1056, 2, 3, O_OBJ_CARRYING_PID);
  RegisterFunction('reg_anim_func', $1057, 2, 0, O_REG_ANIM_FUNC);
  RegisterFunction('reg_anim_animate', $1058, 2, 0, O_REG_ANIM_ANIMATE);
  RegisterFunction('reg_anim_animate_reverse', $1059, 2, 0, O_REG_ANIM_ANIMATE_REV);
  RegisterFunction('reg_anim_obj_move_to_obj', $105A, 2, 0, O_REG_ANIM_MOVE_TO_OBJ);
  RegisterFunction('reg_anim_obj_run_to_obj', $105B, 2, 0, O_REG_ANIM_RUN_TO_OBJ);
  RegisterFunction('reg_anim_obj_move_to_tile', $105C, 3, 0, O_REG_ANIM_MOVE_TO_TILE);
  RegisterFunction('reg_anim_obj_run_to_tile', $105D, 3, 0, O_REG_ANIM_RUN_TO_TILE);
  RegisterFunction('play_gmovie', $105E, 1, 0, O_PLAY_GMOVIE);
  RegisterFunction('add_mult_objs_to_inven', $105F, 3, 0, O_ADD_MULT_OBJS);
  RegisterFunction('rm_mult_objs_from_inven', $1060, 2, 0, O_RM_MULT_OBJS);
  RegisterFunction('get_month', $1061, 0, 1, O_GET_MONTH);
  RegisterFunction('get_day', $1062, 0, 1, O_GET_DAY);
  RegisterFunction('explosion', $1063, 3, 0, O_EXPLOSION);
  RegisterFunction('days_since_visited', $1064, 0, 1, O_DAYS_SINCE_VISITED);
  RegisterFunction('gsay_start', $1065, 0, 0, O_GSAY_START);
  RegisterFunction('gsay_end', $1066, 0, 0, O_GSAY_END);
  RegisterFunction('gsay_reply', $1067, 2, 0, O_GSAY_REPLY);
  RegisterFunction('gsay_option', $1068, 4, 0, O_GSAY_OPTION);
  RegisterFunction('gsay_message', $1069, 3, 0, O_GSAY_MESSAGE);
  RegisterFunction('giq_option', $106A, 5, 0, O_GIQ_OPTION);
  RegisterFunction('poison', $106B, 2, 0, O_POISON);
  RegisterFunction('get_poison', $106C, 1, 1, O_GET_POISON);
  RegisterFunction('party_add', $106D, 1, 0, O_PARTY_ADD);
  RegisterFunction('party_remove', $106E, 1, 0, O_PARTY_REMOVE);
  RegisterFunction('reg_anim_animate_forever', $106F, 2, 0, O_REG_ANIM_FOREVER);
  RegisterFunction('critter_injure', $1070, 2, 0, O_CRITTER_INJURE);
  RegisterFunction('combat_is_initialized', $1071, 0, 1, O_COMBAT_IS_INIT);
  RegisterFunction('gdialog_set_barter_mod', $1072, 1, 0, O_GDIALOG_BARTER_MOD);
  RegisterFunction('difficulty_level', $1073, 0, 1, O_DIFFICULTY_LEVEL);
  RegisterFunction('running_burning_guy', $1074, 1, 3, O_RUNNING_BURNING_GUY);
  RegisterFunction('inven_unwield', $1075, 1, 0, O_INVEN_UNWIELD);
  RegisterFunction('obj_is_locked', $1076, 1, 1, O_OBJ_IS_LOCKED);
  RegisterFunction('obj_lock', $1077, 1, 0, O_OBJ_LOCK);
  RegisterFunction('obj_unlock', $1078, 1, 0, O_OBJ_UNLOCK);
  RegisterFunction('obj_is_open', $1079, 1, 1, O_OBJ_IS_OPEN);
  RegisterFunction('obj_open', $107A, 1, 0, O_OBJ_OPEN);
  RegisterFunction('obj_close', $107B, 1, 0, O_OBJ_CLOSE);
  RegisterFunction('game_ui_disable', $107C, 0, 0, O_GAME_UI_DISABLE);
  RegisterFunction('game_ui_enable', $107D, 0, 0, O_GAME_UI_ENABLE);
  RegisterFunction('game_ui_is_disabled', $107E, 0, 1, O_GAME_UI_IS_DISABLED);
  RegisterFunction('gfade_out', $107F, 2, 0, O_GFADE_OUT);
  RegisterFunction('gfade_in', $1080, 2, 0, O_GFADE_IN);
  RegisterFunction('item_caps_total', $1081, 1, 1, O_ITEM_CAPS_TOTAL);
  RegisterFunction('item_caps_adj', $1082, 2, 0, O_ITEM_CAPS_ADJUST);
  RegisterFunction('anim_action_frame', $1083, 2, 0, O_ANIM_ACTION_FRAME);
  RegisterFunction('reg_anim_play_sfx', $1084, 3, 0, O_REG_ANIM_PLAY_SFX);
  RegisterFunction('critter_mod_skill', $1085, 3, 0, O_CRITTER_MOD_SKILL);
  RegisterFunction('sfx_build_char_name', $1086, 1, 2, O_SFX_BUILD_CHAR_NAME);
  RegisterFunction('sfx_build_ambient_name', $1087, 1, 2, O_SFX_BUILD_AMBIENT);
  RegisterFunction('sfx_build_interface_name', $1088, 1, 2, O_SFX_BUILD_INTERFACE);
  RegisterFunction('sfx_build_item_name', $1089, 1, 2, O_SFX_BUILD_ITEM_NAME);
  RegisterFunction('sfx_build_weapon_name', $108A, 1, 2, O_SFX_BUILD_WEAPON);
  RegisterFunction('sfx_build_scenery_name', $108B, 1, 2, O_SFX_BUILD_SCENERY);
  RegisterFunction('attack_setup', $108C, 2, 0, O_ATTACK_SETUP);
  RegisterFunction('destroy_mult_objs', $108D, 2, 0, O_DESTROY_MULT_OBJS);
  RegisterFunction('use_obj_on_obj', $108E, 2, 0, O_USE_OBJ_ON_OBJ);
  RegisterFunction('endgame_slideshow', $108F, 1, 0, O_ENDGAME_SLIDESHOW);
  RegisterFunction('move_obj_inven_to_obj', $1090, 2, 0, O_MOVE_OBJ_INVEN);
  RegisterFunction('endgame_movie', $1091, 1, 0, O_ENDGAME_MOVIE);
  RegisterFunction('obj_art_fid', $1092, 1, 1, O_OBJ_ART_FID);
  RegisterFunction('art_anim', $1093, 2, 0, O_ART_ANIM);
  RegisterFunction('party_member_obj', $1094, 1, 3, O_PARTY_MEMBER_OBJ);
  RegisterFunction('rotation_to_tile', $1095, 2, 1, O_ROTATION_TO_TILE);
  RegisterFunction('jam_lock', $1096, 1, 0, O_JAM_LOCK);
  RegisterFunction('gdialog_set_barter_mod', $1097, 1, 0, O_GDIALOG_BARTER_MOD);
  RegisterFunction('combat_difficulty', $1098, 0, 1, O_COMBAT_DIFFICULTY);
  RegisterFunction('obj_on_screen', $1099, 1, 1, O_OBJ_ON_SCREEN);
  RegisterFunction('critter_is_fleeing', $109A, 1, 1, O_CRITTER_IS_FLEEING);
  RegisterFunction('critter_set_flee_state', $109B, 2, 0, O_CRITTER_SET_FLEE);
  RegisterFunction('terminate_combat', $109C, 0, 0, O_TERMINATE_COMBAT);
  RegisterFunction('debug_msg', $109D, 1, 0, O_DEBUG_MSG);
  RegisterFunction('critter_stop_attacking', $109E, 1, 0, O_CRITTER_STOP_ATTACK);
  RegisterFunction('start_gdialog', $109F, 5, 0, O_START_GDIALOG);
  RegisterFunction('end_dialogue', $10A0, 0, 0, O_END_DIALOGUE);
  RegisterFunction('dude_is_female', $10A1, 0, 1);
  RegisterFunction('self_attack_dude', $10A2, 0, 0);
  RegisterFunction('obj_in_party', $10A3, 1, 1);
  RegisterFunction('inc_good_critter', $10A4, 0, 0);
  RegisterFunction('floater_rand', $10A5, 2, 0);
end;

end.