unit uBuiltins;

interface

uses
  System.SysUtils, System.Generics.Collections;

type
  TOpcodeBase = Word;

const
  O_OPERATOR    = $8000;
  O_INT         = $4000;
  O_FLOAT       = $2000;
  O_STRING      = $1000;
  O_INTOP       = O_OPERATOR or O_INT;
  O_STRINGOP    = O_OPERATOR or O_STRING;
  O_FLOATOP     = O_OPERATOR or O_FLOAT;

type
  TOpcode = Word;

const
  O_NOOP              = O_OPERATOR + 0;
  O_CONST              = O_OPERATOR + 1;
  O_CRITICAL_START    = O_OPERATOR + 2;
  O_CRITICAL_DONE     = O_OPERATOR + 3;
  O_JMP               = O_OPERATOR + 4;
  O_CALL              = O_OPERATOR + 5;
  O_CALL_AT           = O_OPERATOR + 6;
  O_CALL_CONDITION    = O_OPERATOR + 7;
  O_CALLSTART         = O_OPERATOR + 8;
  O_EXEC              = O_OPERATOR + 9;
  O_SPAWN             = O_OPERATOR + 10;
  O_FORK              = O_OPERATOR + 11;
  O_A_TO_D            = O_OPERATOR + 12;
  O_D_TO_A            = O_OPERATOR + 13;
  O_EXIT              = O_OPERATOR + 14;
  O_DETACH            = O_OPERATOR + 15;
  O_EXIT_PROG         = O_OPERATOR + 16;
  O_STOP_PROG         = O_OPERATOR + 17;
  O_FETCH_GLOBAL     = O_OPERATOR + 18;
  O_STORE_GLOBAL     = O_OPERATOR + 19;
  O_FETCH_EXTERNAL   = O_OPERATOR + 20;
  O_STORE_EXTERNAL   = O_OPERATOR + 21;
  O_EXPORT_VAR       = O_OPERATOR + 22;
  O_EXPORT_PROC      = O_OPERATOR + 23;
  O_SWAP              = O_OPERATOR + 24;
  O_SWAPA             = O_OPERATOR + 25;
  O_POP               = O_OPERATOR + 26;
  O_DUP               = O_OPERATOR + 27;
  O_POP_RETURN       = O_OPERATOR + 28;
  O_POP_EXIT         = O_OPERATOR + 29;
  O_POP_ADDRESS      = O_OPERATOR + 30;
  O_POP_FLAGS        = O_OPERATOR + 31;
  O_POP_FLAGS_RETURN = O_OPERATOR + 32;
  O_POP_FLAGS_EXIT   = O_OPERATOR + 33;
  O_CHECK_ARG_COUNT  = O_OPERATOR + 38;
  O_LOOKUP_STRING_PROC = O_OPERATOR + 39;
  O_POP_BASE         = O_OPERATOR + 40;
  O_PUSH_BASE       = O_OPERATOR + 41;
  O_SET_GLOBAL      = O_OPERATOR + 42;
  O_FETCH_PROC_ADDRESS = O_OPERATOR + 43;
  O_DUMP             = O_OPERATOR + 44;
  O_IF               = O_OPERATOR + 45;
  O_WHILE            = O_OPERATOR + 46;
  O_STORE            = O_OPERATOR + 47;
  O_FETCH            = O_OPERATOR + 48;
  O_EQUAL            = O_OPERATOR + 49;
  O_NOT_EQUAL        = O_OPERATOR + 50;
  O_LESS_EQUAL      = O_OPERATOR + 51;
  O_GREATER_EQUAL   = O_OPERATOR + 52;
  O_LESS            = O_OPERATOR + 53;
  O_GREATER         = O_OPERATOR + 54;
  O_ADD             = O_OPERATOR + 55;
  O_SUB             = O_OPERATOR + 56;
  O_MUL             = O_OPERATOR + 57;
  O_DIV             = O_OPERATOR + 58;
  O_MOD             = O_OPERATOR + 59;
  O_AND             = O_OPERATOR + 60;
  O_OR              = O_OPERATOR + 61;
  O_BWAND           = O_OPERATOR + 62;
  O_BWOR            = O_OPERATOR + 63;
  O_BWXOR           = O_OPERATOR + 64;
  O_BWNOT           = O_OPERATOR + 65;
  O_FLOOR           = O_OPERATOR + 66;
  O_NOT             = O_OPERATOR + 67;
  O_NEGATE          = O_OPERATOR + 68;
  O_WAIT             = O_OPERATOR + 69;
  O_CANCEL          = O_OPERATOR + 70;
  O_CANCELALL       = O_OPERATOR + 71;
  O_STARTCRITICAL   = O_OPERATOR + 72;
  O_ENDCRITICAL     = O_OPERATOR + 73;
  O_END_CORE       = O_OPERATOR + 74;
  O_RET            = O_OPERATOR + 75;
  O_POP_TO_BASE    = O_OPERATOR + 40;

  OP_PUSH_NUMBER    = $01;
  OP_PUSH_STRING    = $02;
  OP_PUSH_VARIABLE  = $03;
  OP_POP            = $04;
  OP_DUP            = $05;
  OP_SWAP            = $06;
  OP_ADD            = $10;
  OP_SUB            = $11;
  OP_MUL            = $12;
  OP_DIV            = $13;
  OP_MOD            = $14;
  OP_NEG            = $15;
  OP_EQ             = $20;
  OP_NE             = $21;
  OP_LT             = $22;
  OP_GT             = $23;
  OP_LE             = $24;
  OP_GE             = $25;
  OP_AND            = $30;
  OP_OR             = $31;
  OP_NOT            = $32;
  OP_JMP            = $40;
  OP_JZ             = $41;
  OP_JNZ            = $42;
  OP_CALL_PROC      = $50;
  OP_CALL_BUILTIN   = $51;
  OP_RET            = $52;
  OP_PUSH_LOCAL    = $60;
  OP_POP_LOCAL     = $61;
  OP_PUSH_GLOBAL   = $62;
  OP_POP_GLOBAL    = $63;
  OP_PUSH_MAPVAR   = $64;
  OP_POP_MAPVAR    = $65;
  OP_PUSH_TEMP     = $66;
  OP_POP_TEMP      = $67;
  OP_NOP            = $FF;

type
  TBuiltinFunction = record
    Name: string;
    OpcodeID: Word;
    ParamCount: Integer;
    ReturnType: Integer;
  end;

  TBuiltinDatabase = class
  private
    FFunctions: TDictionary<string, TBuiltinFunction>;
    FIDMap: TDictionary<Word, TBuiltinFunction>;
  public
    constructor Create;
    destructor Destroy; override;
    procedure RegisterFunction(const AName: string; AID: Word; AParams: Integer; ARetType: Integer);
    function FindByName(const AName: string): TBuiltinFunction;
    function FindByID(AID: Word): TBuiltinFunction;
    procedure InitializeFallout2Builtins;
  end;

implementation

constructor TBuiltinDatabase.Create;
begin
  inherited;
  FFunctions := TDictionary<string, TBuiltinFunction>.Create;
  FIDMap := TDictionary<Word, TBuiltinFunction>.Create;
end;

destructor TBuiltinDatabase.Destroy;
begin
  FFunctions.Free;
  FIDMap.Free;
  inherited;
end;

procedure TBuiltinDatabase.RegisterFunction(const AName: string; AID: Word; AParams: Integer; ARetType: Integer);
var
  Func: TBuiltinFunction;
begin
  Func.Name := AName;
  Func.OpcodeID := AID;
  Func.ParamCount := AParams;
  Func.ReturnType := ARetType;
  FFunctions.AddOrSetValue(LowerCase(AName), Func);
  FIDMap.AddOrSetValue(AID, Func);
end;

function TBuiltinDatabase.FindByName(const AName: string): TBuiltinFunction;
begin
  if not FFunctions.TryGetValue(LowerCase(AName), Result) then
    raise Exception.CreateFmt('Unknown builtin function: %s', [AName]);
end;

function TBuiltinDatabase.FindByID(AID: Word): TBuiltinFunction;
begin
  if not FIDMap.TryGetValue(AID, Result) then
    raise Exception.CreateFmt('Unknown builtin ID: %d', [AID]);
end;

procedure TBuiltinDatabase.InitializeFallout2Builtins;
begin
  RegisterFunction('display_msg', $0001, 1, 0);
  RegisterFunction('debug_msg', $0002, 1, 0);
  RegisterFunction('float_msg', $0003, 3, 0);
  RegisterFunction('message_str', $0004, 2, 2);
  RegisterFunction('message_str_game', $0005, 2, 2);
  RegisterFunction('create_object', $0100, 3, 3);
  RegisterFunction('create_object_sid', $0101, 4, 3);
  RegisterFunction('obj_name', $0102, 1, 2);
  RegisterFunction('obj_art_fid', $0103, 1, 1);
  RegisterFunction('obj_pid', $0104, 1, 1);
  RegisterFunction('obj_is_carrying_obj_pid', $0105, 2, 1);
  RegisterFunction('obj_carrying_pid_obj', $0106, 2, 3);
  RegisterFunction('obj_can_see_obj', $0107, 2, 1);
  RegisterFunction('obj_can_hear_obj', $0108, 2, 1);
  RegisterFunction('attack', $0200, 1, 0);
  RegisterFunction('attack_complex', $0201, 5, 0);
  RegisterFunction('evaluate_attack', $0202, 1, 1);
  RegisterFunction('aim_skill', $0203, 2, 1);
  RegisterFunction('party_add', $0300, 1, 0);
  RegisterFunction('party_remove', $0301, 1, 0);
  RegisterFunction('party_member_obj', $0302, 1, 3);
  RegisterFunction('is_party_member', $0303, 1, 1);
  RegisterFunction('add_obj_to_inven', $0400, 2, 0);
  RegisterFunction('rm_obj_from_inven', $0401, 2, 0);
  RegisterFunction('add_mult_objs_to_inven', $0402, 3, 0);
  RegisterFunction('move_obj_inven_to_obj', $0403, 2, 0);
  RegisterFunction('obj_unequip', $0404, 1, 0);
  RegisterFunction('obj_inven_obj', $0405, 2, 3);
  RegisterFunction('critter_heal', $0500, 2, 0);
  RegisterFunction('critter_dmg', $0501, 3, 0);
  RegisterFunction('critter_set_floating', $0502, 2, 0);
  RegisterFunction('critter_attempt_placement', $0503, 3, 1);
  RegisterFunction('skill_check', $0600, 3, 1);
  RegisterFunction('do_check', $0601, 3, 1);
  RegisterFunction('roll_vs_skill', $0602, 3, 1);
  RegisterFunction('has_skill', $0603, 2, 1);
  RegisterFunction('pc_skill_level', $0604, 2, 1);
  RegisterFunction('local_var', $0700, 1, 1);
  RegisterFunction('set_local_var', $0701, 2, 0);
  RegisterFunction('global_var', $0702, 1, 1);
  RegisterFunction('set_global_var', $0703, 2, 0);
  RegisterFunction('map_var', $0704, 1, 1);
  RegisterFunction('set_map_var', $0705, 2, 0);
  RegisterFunction('game_ticks', $0800, 0, 1);
  RegisterFunction('game_time', $0801, 0, 1);
  RegisterFunction('elevation', $0802, 1, 1);
  RegisterFunction('tile_distance', $0803, 2, 1);
  RegisterFunction('tile_distance_objs', $0804, 2, 1);
  RegisterFunction('dude_obj', $0900, 0, 3);
  RegisterFunction('dude_is_male', $0901, 0, 1);
  RegisterFunction('give_exp_points', $0902, 1, 0);
  RegisterFunction('get_pc_stat', $0903, 1, 1);
  RegisterFunction('has_quest', $0A00, 1, 1);
  RegisterFunction('set_quest', $0A01, 1, 0);
  RegisterFunction('rep_good', $0A02, 0, 1);
  RegisterFunction('rep_bad', $0A03, 0, 1);
  RegisterFunction('rep_good_vault', $0A04, 0, 1);
  RegisterFunction('add_timer_event', $0B00, 3, 0);
  RegisterFunction('rm_timer_event', $0B01, 1, 0);
  RegisterFunction('fix_timer_event', $0B02, 4, 0);
  RegisterFunction('random', $0C00, 2, 1);
  RegisterFunction('metarule', $0C01, 2, 1);
  RegisterFunction('metarule3', $0C02, 4, 1);
  RegisterFunction('script_action', $0C03, 0, 1);
  RegisterFunction('obj_is_locked', $0C04, 1, 1);
  RegisterFunction('obj_lock', $0C05, 1, 0);
  RegisterFunction('obj_unlock', $0C06, 1, 0);
  RegisterFunction('give_exp_points', $1000, 1, 0);
  RegisterFunction('scr_return', $1001, 0, 0);
  RegisterFunction('play_sfx', $1002, 2, 0);
  RegisterFunction('obj_name', $1003, 1, 2);
  RegisterFunction('sfx_build_open_name', $1004, 1, 2);
  RegisterFunction('get_pc_stat', $1005, 1, 1);
  RegisterFunction('tile_contains_pid_obj', $1006, 2, 3);
  RegisterFunction('set_map_start', $1007, 3, 0);
  RegisterFunction('override_map_start', $1008, 3, 0);
  RegisterFunction('has_skill', $1009, 2, 1);
  RegisterFunction('using_skill', $100A, 1, 1);
  RegisterFunction('roll_vs_skill', $100B, 3, 1);
  RegisterFunction('skill_contest', $100C, 3, 1);
  RegisterFunction('do_check', $100D, 3, 1);
  RegisterFunction('is_success', $100E, 0, 1);
  RegisterFunction('is_critical', $100F, 0, 1);
  RegisterFunction('how_much', $1010, 0, 1);
  RegisterFunction('mark_area_known', $1011, 2, 0);
  RegisterFunction('reaction', $1012, 0, 1);
  RegisterFunction('random', $1013, 2, 1);
  RegisterFunction('roll_dice', $1014, 3, 1);
  RegisterFunction('move_to', $1015, 2, 0);
  RegisterFunction('create_object_sid', $1016, 4, 3);
  RegisterFunction('display_msg', $1017, 1, 0);
  RegisterFunction('script_overrides', $1018, 0, 1);
  RegisterFunction('obj_is_carying_obj_pid', $1019, 2, 1);
  RegisterFunction('tile_contains_obj_pid', $101A, 2, 1);
  RegisterFunction('self_obj', $101B, 0, 3);
  RegisterFunction('source_obj', $101C, 0, 3);
  RegisterFunction('target_obj', $101D, 0, 3);
  RegisterFunction('dude_obj', $101E, 0, 3);
  RegisterFunction('obj_being_used_with', $101F, 2, 3);
  RegisterFunction('local_var', $1020, 1, 1);
  RegisterFunction('set_local_var', $1021, 2, 0);
  RegisterFunction('map_var', $1022, 1, 1);
  RegisterFunction('set_map_var', $1023, 2, 0);
  RegisterFunction('global_var', $1024, 1, 1);
  RegisterFunction('set_global_var', $1025, 2, 0);
  RegisterFunction('script_action', $1026, 0, 1);
  RegisterFunction('obj_type', $1027, 1, 1);
  RegisterFunction('obj_item_subtype', $1028, 1, 1);
  RegisterFunction('get_critter_stat', $1029, 2, 1);
  RegisterFunction('set_critter_stat', $102A, 3, 0);
  RegisterFunction('animate_stand_obj', $102B, 1, 0);
  RegisterFunction('animate_stand_reverse_obj', $102C, 1, 0);
  RegisterFunction('animate_move_obj_to_tile', $102D, 3, 0);
  RegisterFunction('tile_in_tile_rect', $102E, 5, 1);
  RegisterFunction('metarule3', $102F, 4, 1);
  RegisterFunction('set_map_music', $1030, 2, 0);
  RegisterFunction('anim_busy', $1031, 1, 0);
  RegisterFunction('critter_heal', $1032, 2, 0);
  RegisterFunction('set_light_level', $1033, 1, 0);
  RegisterFunction('game_time', $1034, 0, 1);
  RegisterFunction('game_time_in_seconds', $1035, 0, 1);
  RegisterFunction('elevation', $1036, 1, 1);
  RegisterFunction('kill_critter', $1037, 1, 0);
  RegisterFunction('kill_critter_type', $1038, 2, 0);
  RegisterFunction('critter_dmg', $1039, 3, 0);
  RegisterFunction('add_timer_event', $103A, 3, 0);
  RegisterFunction('rm_timer_event', $103B, 1, 0);
  RegisterFunction('game_ticks', $103C, 0, 1);
  RegisterFunction('has_trait', $103D, 2, 1);
  RegisterFunction('destroy_object', $103E, 1, 0);
  RegisterFunction('obj_can_hear_obj', $103F, 2, 1);
  RegisterFunction('game_time_hour', $1040, 0, 1);
  RegisterFunction('fixed_param', $1041, 0, 1);
  RegisterFunction('tile_is_visible', $1042, 2, 1);
  RegisterFunction('dialogue_system_enter', $1043, 0, 0);
  RegisterFunction('action_being_used', $1044, 1, 3);
  RegisterFunction('critter_state', $1045, 1, 1);
  RegisterFunction('game_time_advance', $1046, 1, 0);
  RegisterFunction('radiation_inc', $1047, 2, 0);
  RegisterFunction('radiation_dec', $1048, 2, 0);
  RegisterFunction('critter_attempt_placement', $1049, 3, 1);
  RegisterFunction('obj_pid', $104A, 1, 1);
  RegisterFunction('cur_map_index', $104B, 0, 1);
  RegisterFunction('critter_add_trait', $104C, 3, 0);
  RegisterFunction('critter_rm_trait', $104D, 3, 0);
  RegisterFunction('proto_data', $104E, 2, 1);
  RegisterFunction('message_str', $104F, 2, 2);
  RegisterFunction('critter_inven_obj', $1050, 2, 3);
  RegisterFunction('obj_set_light_level', $1051, 2, 0);
  RegisterFunction('world_map', $1052, 0, 0);
  RegisterFunction('float_msg', $1053, 3, 0);
  RegisterFunction('metarule', $1054, 2, 1);
  RegisterFunction('anim', $1055, 2, 0);
  RegisterFunction('obj_carying_pid_obj', $1056, 2, 3);
  RegisterFunction('reg_anim_func', $1057, 2, 0);
  RegisterFunction('reg_anim_animate', $1058, 2, 0);
  RegisterFunction('reg_anim_animate_reverse', $1059, 2, 0);
  RegisterFunction('reg_anim_obj_move_to_obj', $105A, 2, 0);
  RegisterFunction('reg_anim_obj_run_to_obj', $105B, 2, 0);
  RegisterFunction('reg_anim_obj_move_to_tile', $105C, 3, 0);
  RegisterFunction('reg_anim_obj_run_to_tile', $105D, 3, 0);
  RegisterFunction('play_gmovie', $105E, 1, 0);
  RegisterFunction('add_mult_objs_to_inven', $105F, 3, 0);
  RegisterFunction('rm_mult_objs_from_inven', $1060, 2, 0);
  RegisterFunction('get_month', $1061, 0, 1);
  RegisterFunction('get_day', $1062, 0, 1);
  RegisterFunction('explosion', $1063, 3, 0);
  RegisterFunction('days_since_visited', $1064, 0, 1);
  RegisterFunction('gsay_start', $1065, 0, 0);
  RegisterFunction('gsay_end', $1066, 0, 0);
  RegisterFunction('gsay_reply', $1067, 2, 0);
  RegisterFunction('gsay_option', $1068, 4, 0);
  RegisterFunction('gsay_message', $1069, 3, 0);
  RegisterFunction('giq_option', $106A, 4, 0);
  RegisterFunction('poison', $106B, 2, 0);
  RegisterFunction('get_poison', $106C, 1, 1);
  RegisterFunction('party_add', $106D, 1, 0);
  RegisterFunction('party_remove', $106E, 1, 0);
  RegisterFunction('reg_anim_animate_forever', $106F, 2, 0);
  RegisterFunction('critter_injure', $1070, 2, 0);
  RegisterFunction('combat_is_initialized', $1071, 0, 1);
  RegisterFunction('gdialog_set_barter_mod', $1072, 1, 0);
  RegisterFunction('difficulty_level', $1073, 0, 1);
  RegisterFunction('running_burning_guy', $1074, 1, 3);
  RegisterFunction('inven_unwield', $1075, 1, 0);
  RegisterFunction('obj_is_locked', $1076, 1, 1);
  RegisterFunction('obj_lock', $1077, 1, 0);
  RegisterFunction('obj_unlock', $1078, 1, 0);
  RegisterFunction('obj_is_open', $1079, 1, 1);
  RegisterFunction('obj_open', $107A, 1, 0);
  RegisterFunction('obj_close', $107B, 1, 0);
  RegisterFunction('game_ui_disable', $107C, 0, 0);
  RegisterFunction('game_ui_enable', $107D, 0, 0);
  RegisterFunction('game_ui_is_disabled', $107E, 0, 1);
  RegisterFunction('gfade_out', $107F, 2, 0);
  RegisterFunction('gfade_in', $1080, 2, 0);
  RegisterFunction('item_caps_total', $1081, 1, 1);
  RegisterFunction('item_caps_adj', $1082, 2, 0);
  RegisterFunction('anim_action_frame', $1083, 2, 0);
  RegisterFunction('reg_anim_play_sfx', $1084, 3, 0);
  RegisterFunction('critter_mod_skill', $1085, 3, 0);
  RegisterFunction('sfx_build_char_name', $1086, 1, 2);
  RegisterFunction('sfx_build_ambient_name', $1087, 1, 2);
  RegisterFunction('sfx_build_interface_name', $1088, 1, 2);
  RegisterFunction('sfx_build_item_name', $1089, 1, 2);
  RegisterFunction('sfx_build_weapon_name', $108A, 1, 2);
  RegisterFunction('sfx_build_scenery_name', $108B, 1, 2);
  RegisterFunction('attack_setup', $108C, 2, 0);
  RegisterFunction('destroy_mult_objs', $108D, 2, 0);
  RegisterFunction('use_obj_on_obj', $108E, 2, 0);
  RegisterFunction('endgame_slideshow', $108F, 1, 0);
  RegisterFunction('move_obj_inven_to_obj', $1090, 2, 0);
  RegisterFunction('endgame_movie', $1091, 1, 0);
  RegisterFunction('obj_art_fid', $1092, 1, 1);
  RegisterFunction('art_anim', $1093, 2, 0);
  RegisterFunction('party_member_obj', $1094, 1, 3);
  RegisterFunction('rotation_to_tile', $1095, 2, 1);
  RegisterFunction('jam_lock', $1096, 1, 0);
  RegisterFunction('gdialog_set_barter_mod', $1097, 1, 0);
  RegisterFunction('combat_difficulty', $1098, 0, 1);
  RegisterFunction('obj_on_screen', $1099, 1, 1);
  RegisterFunction('critter_is_fleeing', $109A, 1, 1);
  RegisterFunction('critter_set_flee_state', $109B, 2, 0);
  RegisterFunction('terminate_combat', $109C, 0, 0);
  RegisterFunction('debug_msg', $109D, 1, 0);
  RegisterFunction('critter_stop_attacking', $109E, 1, 0);
end;

end.